apiVersion: v1
data:
  tailscale-lb.ini.tpl: |
    # This is the hostname that will show up in the Tailscale console
    # and be used by MagicDNS.
    hostname = tailscale-lb

    # (Optional) Use an authentication key from https://login.tailscale.com/admin/settings/keys
    auth-key = ${TAILSCALE_AUTH_KEY}

    [tcp 443]
    backend = example.com
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: tailscale-lb
    app.kubernetes.io/instance: tailscale-lb
  name: tailscale-lb
  namespace: tailscale-lb
