apiVersion: v1
data:
  TAILSCALE_AUTH_KEY: Q0hBTkdFTUUK
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: tailscale-lb
    app.kubernetes.io/instance: tailscale-lb
  name: tailscale-lb
  namespace: tailscale-lb
type: Opaque
