name: Build
on:
  push:
    branches:
      - '**'
    paths:
      - '**'
      - '!.github/**'
      - '!.gitignore'
      - '!infra/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  nix-build:
    name: nix build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Authenticate to Google Cloud Platform
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ vars.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GOOGLE_SERVICE_ACCOUNT }}
          token_format: access_token
      - name: Install Nix
        uses: cachix/install-nix-action@v26
      - name: Set up cache
        uses: zombiezen/setup-nix-cache-action@v0.3.0
        with:
          substituters: ${{ vars.NIX_SUBSTITUTER }}
          secret_keys: ${{ secrets.NIX_PRIVATE_KEY }}
          use_nixcached: true
      - id: build
        name: Build and test
        run: |
          nix build --print-build-logs '.#ci'
          echo "result=$(readlink -f result)" >> "$GITHUB_OUTPUT"
      - name: Upload Docker images
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: ${{ steps.build.outputs.result }}/docker-image-*.tar.gz

permissions:
  contents: read
  id-token: write
